export const LOGIN = "LOGIN";
export const REGISTER = "REGISTER";
export const FAIL = "FAIL";
export const LOADING = "LOADING";

export const PASSWORD_SUCCESS = "PASSWORD_SUCCESS";
export const PASSWORD_FAIL = "PASSWORD_FAIL";

export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";

export const LOGOUT = "LOGOUT";

export const AVATAR_SUCCESS = "AVATAR_SUCCESS";
export const AVATAR_FAIL = "AVATAR_FAIL";

export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const ADD_OFFER_SUCCESS = "ADD_OFFER_SUCCESS";
export const ADD_OFFER_FAIL = "ADD_OFFER_FAIL";

export const REMOVE_USER_ERROR = "REMOVE_USER_ERROR";

export const GET_PHOTOGRAPHER_SUCCESS = "GET_PHOTOGRAPHER_SUCCESS";
export const GET_PHOTOGRAPHER_FAIL = "GET_PHOTOGRAPHER_FAIL";

export const GET_DECORATOR_SUCCESS = "GET_DECORATOR_SUCCESS";
export const GET_DECORATOR_FAIL = "GET_DECORATOR_FAIL";

export const GET_ANIMATOR_SUCCESS = "GET_ANIMATOR_SUCCESS";
export const GET_ANIMATOR_FAIL = "GET_ANIMATOR_FAIL";

export const GET_PASTRY_SUCCESS = "GET_PASTRY_SUCCESS";
export const GET_PASTRY_FAIL = "GET_PASTRY_FAIL";

export const ADD_GALLERY_SUCCESS = "ADD_GALLERY_SUCCESS";
export const ADD_GALLERY_FAIL = "ADD_GALLERY_FAIL";

export const GET_GALLERY_SUCCESS = "GET_GALLERY_SUCCESS";
export const GET_GALLERY_FAIL = "GET_GALLERY_FAIL";

export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL";

export const CONTACT_US_SUCCESS = "CONTACT_US_SUCCESS";
export const CONTACT_US_FAIL = "CONTACT_US_FAIL";

export const REMOVE_ERROR = "REMOVE_ERROR";

export const DELETE_OFFER_SUCCESS = "DELETE_OFFER_SUCCESS";
export const DELETE_OFFER_FAIL = "DELETE_OFFER_FAIL";

export const GET_OFFER_SUCCESS = "GET_OFFER_SUCCESS";
export const GET_OFFER_FAIL = "GET_OFFER_FAIL";

export const DELETE_GALLERY_SUCCESS = "DELETE_GALLERY_SUCCESS";
export const DELETE_GALLERY_FAIL = "DELETE_GALLERY_FAIL";

export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_FAIL = "ADD_COMMENT_FAIL";

export const GET_COMMENT_SUCCESS = "GET_COMMENT_SUCCESS";
export const GET_COMMENT_FAIL = "GET_COMMENT_FAIL";

export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_FAIL = "DELETE_COMMENT_FAIL";

export const EDIT_COMMENT_SUCCESS = "EDIT_COMMENT_SUCCESS";
export const EDIT_COMMENT_FAIL = "EDIT_COMMENT_FAIL";

export const REMOVE = "REMOVE";
